-- MySQL Script generated by MySQL Workbench
-- Tue Jul 12 17:47:24 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering



-- -----------------------------------------------------
-- Schema cinemadb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cinemadb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cinemadb` DEFAULT CHARACTER SET utf8 ;
USE `cinemadb` ;

-- -----------------------------------------------------
-- Table `cinemadb`.`movies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies` (
  `idmovie` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) ,
  `desc` VARCHAR(255) ,
  `time` DATETIME ,
  `imgurl` VARCHAR(255) ,
  `categorie` VARCHAR(45) ,
  PRIMARY KEY (`idmovie`));



-- -----------------------------------------------------
-- Table `cinemadb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `idusers` INT NOT NULL AUTO_increment ,
  `username` VARCHAR(45) ,
  `password` VARCHAR(45) ,
  `email` VARCHAR(45) ,
  `idmovie` INT ,
  PRIMARY KEY (`idusers`),
  INDEX `idmovie_idx` (`idmovie` ASC) VISIBLE,
  CONSTRAINT `idmovie`
    FOREIGN KEY (`idmovie`)
    REFERENCES `cinemadb`.`movies` (`idmovie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

INSERT INTO users (username,password,email,idmovie) VALUES ('haythem','password','email',1);
-- CREATE TABLE IF NOT EXISTS public.users
-- (
--     iduser integer NOT NULL DEFAULT nextval('users_iduser_seq'::regclass),
--     username character varying(20) COLLATE pg_catalog."default" NOT NULL,
--     "email " character varying(20) COLLATE pg_catalog."default",
--     password character varying(10) COLLATE pg_catalog."default",
--     "id movie" integer NOT NULL DEFAULT nextval('"users_id movie_seq"'::regclass),
--     CONSTRAINT users_pkey PRIMARY KEY (iduser)
-- )

-- CREATE TABLE IF NOT EXISTS public.movies
-- (
--     idmovie integer NOT NULL DEFAULT nextval('movies_idmovie_seq'::regclass),
--     name character varying(40)[] COLLATE pg_catalog."default" NOT NULL,
--     "desc" character varying(255) COLLATE pg_catalog."default",
--     categorie character varying(20) COLLATE pg_catalog."default",
--     imgurl character varying(255)[] COLLATE pg_catalog."default",
--     CONSTRAINT movies_pkey PRIMARY KEY (idmovie)
-- )